all: Hausaufgabe Hausuebung

Hausaufgabe: 
	g++ Aufgabe1.cpp -o Hausaufgabe
	
Hausuebung:
	g++ Aufgabe11.cpp -o Hausuebung


test: Hausuebung Hausaufgabe
	./Hausaufgabe
	./Hausuebung
	

clean: 
	rm -f aufgabe1
